---
#########
# s390x #
#########

- name: Download Protocol Buffers v3.7.1
  get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-cpp-3.7.1.tar.gz
    dest: /tmp/protobuf-cpp-3.7.1.tar.gz
    force: no
    mode: 0755
    validate_certs: no
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu" or ansible_distribution == "SLES")
  tags: protobuf

- name: Extract Protocol Buffers v3.7.1
  unarchive:
    src: /tmp/protobuf-cpp-3.7.1.tar.gz
    dest: /tmp
    copy: False
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu" or ansible_distribution == "SLES")
  tags: protobuf

- name: Build and install Protocol Buffers v3.7.1
  shell: cd /tmp/protobuf-3.7.1 && ./configure --disable-shared --with-pic && make && make install && ldconfig
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu" or ansible_distribution == "SLES")
  tags: protobuf

- name: Remove downloaded packages for Protocol Buffers v3.7.1
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/protobuf-cpp-3.7.1.tar.gz
    - /tmp/protobuf-3.7.1
  ignore_errors: yes
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu" or ansible_distribution == "SLES")
  tags: protobuf
